### ISSUE TITLE
Unable to use CDP : Target.getBrowserContexts and Target.createBrowserContext

### ISSUE THREAD

**Issue by gdszps** [fake-name/ChromeController#16]
Unable to use CDP : Target.getBrowserContexts and Target.createBrowserContext

Sample：
```
with ChromeController.ChromeContext(binary="/Users/mac/PycharmProjects/myti/Google\ Chrome.app/Contents/MacOS/Google\ Chrome --disable-web-security", additional_options=additional_options,headless=False) as cr:
    print(cr.Target_getBrowserContexts())
```
result:
{'error': {'code': -32000, 'message': 'Not allowed'}, 'id': 4}

**Comment by fake-name** [comment]
That's chrome complaining about permissions, not a library issue. 

I'm not clear exactly what the browser contexts are in this context, but I suspect you either need to enable that particular debug flag with a command line argument, or another function call before trying to call the function in question.

**Comment by fake-name** [comment]
Ok, https://github.com/ChromeDevTools/devtools-protocol/issues/43 seems to indicate those functions are only available in headless chrome.

**Comment by gdszps** [comment]
I would like to ask why I use the runtime.evaluat of other libraries to modify the xhr cookie, and the "Refused to set unsafe header "Cookie"" will appear, but your library will not?

**Comment by gdszps** [comment]
> Ok, [ChromeDevTools/devtools-protocol#43](https://github.com/ChromeDevTools/devtools-protocol/issues/43) and https://github.com/puppeteer/puppeteer/issues/85seem to indicate those functions are only available in headless chrome.
> 
> Puppeteer seems to have worked around this issue by using separate incognito browser windows when running in headfull. mode. Maybe try that?

ws://127.0.0.1:9922/devtools/browser/8f5d781a-7bca-4bfa-9ca5-b835ba9445d2

Only by connecting chrome in this way can Target.createBrowserContext be used

**Comment by fake-name** [comment]
Huh, I currently do not upen a websocket connection to the browser websocket context, just `ws://localhost:21729/devtools/page/680BDAE0D5166C2B37BBEAC773DE5348` and such. 

Exposing that would require having a browser object that owns the underlying tabs, which is a decent idea but I likely won't have time to implement it in the near future.
