### ISSUE TITLE
A terminal window will show on windows

### ISSUE THREAD

**Issue by PaleNeutron** [fake-name/ChromeController#18]
I found that if we redirect stdin, stdout, stderr in `Popen`, a console window will show in windows.

https://github.com/fake-name/ChromeController/blob/049a7aa803eb3913e1f73093fa5e2e5839a52d51/ChromeController/transport.py#L178-L185

Can we hide this window by either stop redirecting or pass hiding flag to it? That would be much more graceful.

**Comment by fake-name** [comment]
I've never run it in a context where I didn't already have a terminal window from which python is executing. .

Also, I've found the stdout of chrome to be useful when it's doing something unexpected, but that's just me.

**Comment by PaleNeutron** [comment]
If you just want to display Chrome std output to python console，you could remove all redirection from code, since it would still show in python console.

**Comment by fake-name** [comment]
Uh, ok? I'd be happy to accept a PR that does that change, but it's not something I'd pursue myself.
