### ISSUE TITLE
How can one run this without a vendored headless_shell ?

### ISSUE THREAD

**Issue by GuacheSuede** [fake-name/ChromeController#2]
Am using a normal chrome instance with debugging 9222 protocol.

**Comment by GuacheSuede** [comment]
Am using a normal chrome instance with debugging 9222 protocol.

**Comment by GuacheSuede** [comment]
It somehow needs a binary, can this connect to Chrome without a binary but a port number instead ?

**Comment by GuacheSuede** [comment]
Found the solution to it. however am getting runtime errors with could not start chromium

**Comment by fake-name** [comment]
See the documentation:

> __init__(self, *args, **kwargs)
> Base chromium transport initialization.
> 
> The binary to execute is assumed to be named `chromium`, and on $PATH
if not specified in the `binary` parameter.
> 
> The chromium binary is launched with the arg `--remote-debugging-port=9222` if found.

(https://fake-name.github.io/ChromeController/ChromeController.CromeRemoteDebugInterface.html)

So you'd construct the interface `ChromeController.ChromeRemoteDebugInterface(binary=crbin)` or `ChromeController.ChromeRemoteDebugInterface(crbin)`, where `crbin` is the path to your chrome binary. 

The interface expects to manage the chromium process lifetime. I don't see any reason it couldn't be possible to have it connect to a running chromium instance, but that's not implemented at the moment.
